namespace SDSLib.Resources.Constants;

public static class JsonKeys {
    public const char Separator = ':';

    public const string Id = "id",
        Backgrounds = "backgrounds",
        Audio = "audio",
        Characters = "characters",
        Dialogues = "dialogues",
        Screens = "screens",
        When = "when",
        Scenes = "scenes",
        Priority = "priority",
        DisplayName = "display_name",
        Textures = "textures",
        Nodes = "nodes",
        Who = "who",
        Lines = "lines",
        Choices = "choices",
        Next = "next",
        JsonExtension = ".json",
        Fonts = "fonts",
        Widgets = "widgets",
        Image = "image",
        Button = "button",
        TextBox = "textbox",
        Stack = "stack",
        Type = "type",
        Anchor = "anchor",
        Action = "action",
        Text = "text",
        Orientation = "orientation",
        Spacing = "spacing",
        Children = "children",
        Width = "width",
        Height = "height",
        Role = "role",
        Dialogue = "dialogue";
}